default_install_hook_types:
- pre-push # if you want to run before a push
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
-  repo: https://github.com/golangci/golangci-lint
   rev: v1.56.1
   hooks:
     - id: golangci-lint-full
       args: [--timeout=5m]
